services:
  - type: web
    plan: free
    name: gif_shop
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn gif_shop.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        value: "{{DATABASE_URL}}"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SECRET_KEY
        value: "{{DJANGO_SECRET_KEY}}"
      - key: DJANGO_DEBUG
        value: 0
      - key: PRODUCTION_HOSTS
        value: ".onrender.com"